[profile.default]
src = "assets/praxis"
out = "out"
libs = ["lib"]
solc = "0.8.20"
evm_version = "paris"
ffi = true
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
atlantic = "https://atlantic.dplabs-internal.com"

[etherscan]
atlantic = { key = "${ETHERSCAN_API_KEY}", url = "https://api.socialscan.io/pharos-atlantic-testnet/v1/explorer/command_api/contract", chain = 688689 }
